<?php
module_load_include('inc', 'cassiopeia_reports', 'cassiopeia_reports');
function cassiopeia_reports_menu() {
  $items = array();

  $items['bao-cao-sl-nhan-vien'] = array(
    'title' => 'Báo cáo số lượng nhân viên theo phòng ban',
    'page callback' => 'cassiopeia_reports_page_list',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['bao-cao-sl-du-an'] = array(
  'title' => 'Báo cáo số dự án theo phòng ban',
  'page callback' => 'cassiopeia_reports_page_task_list',
  'access arguments' => array('access content'),
  'type' => MENU_CALLBACK,
);

 $items['bao-cao-nv-theo-du-an'] = array(
    'title' => 'Báo cáo nhân viên theo dự án',
    'page callback' => 'cassiopeia_reports_page_employee_task',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );


  return $items;
}